---
- name: Install Apache and start service
  hosts: webservers
  vars:
    install_apache: yes
  tasks:
    - name: Install block
      block:
        - name: Install httpd package
          yum: 
            name: httpd
            state: latest


        - name: Copy index file
          copy:
            src: files/index-not-exist-file.html
            dest: /var/www/html/index.html
          register: copy_module_output


        - name: Start httpd service
          service:
            name: httpd
            state: restarted
            enabled: yes 
          when: copy_module_output.changed
      rescue:

        - name: New block
          block: 
            - name: Rescue block error message
              shell:  echo "Apache kurulurken hata alinmistir, lutfen kontrol ediniz"
              register: echo_output
              failed_when: "'hata alinmistir' in echo_output.stdout"
          rescue:
            - name: Second rescue
              debug:
                msg: Second rescue tetiklendi.
      always: 
        - name: End of play
          debug:
            msg: "Playbook tasklari tamamlanmistir."
      when: install_apache 


